
cache:
  paths:
    - ~/.m2/repository/

stages:
  - deploy

deploy-job:
  image: docker:20.10.16
  stage: deploy
  services:
    - name: docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/main:CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/main:CI_COMMIT_SHORT_SHA
