
cache:
  paths:
    - ~/.m2/repository/

stages:
  - check
  - test
  - build
  - deploy

maven-check:
  stage: check
  image: maven:3.6.3-jdk-11
  script:
    - mvn checkstyle:checkstyle
  artifacts:
    paths:
      - target/

maven-test-job:
    stage: test
    image: maven:3.6.3-jdk-11
    script:
        - mvn test
    artifacts:
        paths:
        - target/

maven-build-job:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - echo "Compiling the code..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  image: docker:20.10.16
  stage: deploy
  services:
    - name: docker:dind
  script:
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker build -t $CI_REGISTRY_IMAGE/mr:CI_COMMIT_SHORT_SHA .
   - docker push $CI_REGISTRY_IMAGE/mr:CI_COMMIT_SHORT_SHA
