version: "2.2"

services:
  postgres:
    image: postgres:14.1
    volumes:
      - postgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
  spring-petclinic:
    image: second_image:latest
    ports:
      - "8080:8080"

volumes:
  postgdata:
    driver: local
